### ISSUE TITLE
flag.sh: "-fstack-check" always added when using clang

### ISSUE THREAD

**Issue by huglovefan** [vaeth/portage-bashrc-mv#22] opened 2020-03-18 10:25 UTC
https://github.com/vaeth/portage-bashrc-mv/blob/8c057e7b63d54a65061225c580c25b64f2de6ac1/bashrc.d/10-flag.sh#L597

i guess this is meant to replace flags like `-fstack-check=all` with just `-fstack-check` for clang compatibility but it's unconditionally enabling stack checking for me (i don't want it)

you can test it by doing `CC=clang CFLAGS=-O2 emerge -1 portage-bashrc-mv` and looking at the flags it prints

`category/package /-flag1/-flag2` in package.cflags does the same thing where it always adds `-flag2` (i expected it would add `-flag2` only if `-flag1` was present)

using `portage-bashrc-mv-19.1` and `bash-4.4_p23-r1`

**Comment by vaeth** [comment] 2020-03-22 06:00
The behaviour of `/-flag1/-flag2` was as intended and documented.
However, I agree that this is undesired for -fstack-check.

I decided to fix the latter by changing the functionality of `/-flag1/-flag2` to not append `-flags2` (if `-flag1` cannot be replaced): The old behavior can be achieved by the new one easily with `/-flag1/-flag2 -flag2` while the new behavior could not be easily achieved at all.

In this sense, the issue should be fixed in v20.0

**Closed by vaeth** 2020-03-22 06:00 UTC
